# ex03 - Récupération de données avec SELECT

Lorsque vous travaillez avec des bases de données et SQL, la tâche la plus courante consiste à demander des données à une ou plusieurs tables, ce qui renvoie ces données sous la forme d'une table de résultats. 

Ces tables de résultats sont appelées result-sets (ensembles de résultats).

L'instruction ***SELECT*** accomplit cela. 

Dans la plupart des applications, ***SELECT*** est la commande de langage de requête de données (DQL) la plus couramment utilisée.

De plus, ***SELECT*** peut faire bien plus que juste récupérer et afficher des données, nous le verrons dans les sections suivantes.

***Syntaxe de la commande SELECT***

- *SELECT colonne1, colonne2, colonneN FROM nom_table;*

Ici : colonne1, colonne2 ... sont les champs (colonnes) de la table (nom_table).

Mais si vous souhaitez interroger tous les enregistrements, utilisez simplement:
- SELECT * FROM nom_table;

In [2]:
%load_ext sql

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

### 0. Reconnectons notre Google Drive

In [3]:
from google.colab import drive
# drive.mount('/content/gdrive')
drive.mount("/content/gdrive", force_remount=True)

Mounted at /content/gdrive

### 1. Connexion à la Database fournie pour le TP : demo.db3

In [4]:
%sql sqlite:////content/gdrive/MyDrive/Partage/Notebooks_Serie_1/demo.db3

'Connected: @/content/gdrive/MyDrive/Partage/Notebooks_Serie_1/demo.db3'

Si vous ne connaissez pas les tables présentes dans la database de démonstration, vous pouvez toujours utiliser la commande suivante pour le savoir.

In [5]:
%sql SELECT name FROM sqlite_master WHERE type='table'

 * sqlite:////content/gdrive/MyDrive/Partage/Notebooks_Serie_1/demo.db3
Done.

[('rch',),
 ('hru',),
 ('sub',),
 ('sed',),
 ('watershed_daily',),
 ('watershed_monthly',),
 ('watershed_yearly',),
 ('channel_dimension',),
 ('hru_info',),
 ('sub_info',),
 ('rch_info',),
 ('ave_plant',),
 ('ave_annual_hru',),
 ('ave_monthly_basin',),
 ('ave_annual_basin',),
 ('sqlite_sequence',),
 ('watershed_yearly_bk',),
 ('Temperature',)]



Ici, nous sélectionnons la table ***Watershed_yearly*** comme exemple.

### 2. Récupération de toutes les données
Comme nous le savons déjà, l'opération SQL la plus courante est une instruction SELECT, qui extrait des données d'une table, puis affiche les résultats. 

Lançons donc cette requête SQL :

In [6]:
%sql SELECT * From watershed_yearly

 * sqlite:////content/gdrive/MyDrive/Partage/Notebooks_Serie_1/demo.db3
Done.

[(1981, 895.6051025390625, 130.3574676513672, 51.33439254760742, 406.0739440917969, 443.198486328125, 0.0, 18819.70703125, 236.98300170898438, 840.6874389648438, 609.706787109375, 91.08026123046875, 0.03293686360120773, 0.06417319178581238, 5.615890026092529, 7.339915752410889, 11.857464790344238, 0.008220621384680271, 1.461671233177185, 0.0),
 (1982, 884.670654296875, 92.21265411376953, 50.34769058227539, 367.41070556640625, 424.6783752441406, 0.0, 19425.8359375, 256.79083251953125, 872.07470703125, 530.0245971679688, 64.80978393554688, 0.00797836109995842, 0.04918050765991211, 4.239809036254883, 7.676506042480469, 10.873835563659668, 0.007697358727455139, 1.343782901763916, 0.0),
 (1983, 816.6605224609375, 129.16310119628906, 54.47308349609375, 445.33306884765625, 462.76324462890625, 0.0, 18476.1953125, 237.70555114746094, 797.04736328125, 652.8157958984375, 92.04792785644531, 0.13790887594223022, 0.048595353960990906, 3.882063388824463, 7.301627159118652, 12.202207565307617, 0.015354366973042488, 1.5196093320846558, 0.0),
 (1984, 867.5743408203125, 95.57946014404297, 46.948646545410156, 347.2448425292969, 408.5397033691406, 0.0, 17727.712890625, 223.08975219726562, 911.25634765625, 510.37933349609375, 63.0908203125, 0.01470834668725729, 0.0440557599067688, 5.141480922698975, 6.492110729217529, 10.941608428955078, 0.011575199663639069, 1.3742408752441406, 0.0),
 (1985, 637.7255249023438, 75.55760192871094, 45.336883544921875, 358.2953186035156, 361.4852294921875, 0.0, 15840.5400390625, 236.32135009765625, 990.8557739257812, 499.33990478515625, 49.63069152832031, 0.05470645800232887, 0.046555422246456146, 3.113034963607788, 6.522554874420166, 8.959033966064453, 0.010798747651278973, 1.1150814294815063, 0.0),
 (1986, 733.8412475585938, 65.63016510009766, 36.76259231567383, 241.9388427734375, 281.6683349609375, 0.0, 16059.4345703125, 243.0305633544922, 977.513427734375, 358.09368896484375, 48.7893180847168, 0.0010510582942515612, 0.040558818727731705, 2.8865158557891846, 6.505890369415283, 7.870068073272705, 0.013286528177559376, 0.970182478427887, 0.0),
 (1987, 1007.8944702148438, 110.28632354736328, 62.23741912841797, 445.5394592285156, 493.0043029785156, 0.0, 19541.869140625, 256.9570007324219, 841.0055541992188, 641.2118530273438, 76.02854919433594, 0.013590915128588676, 0.05216805264353752, 3.6147713661193848, 5.987320899963379, 14.57848834991455, 0.019578929990530014, 1.8156678676605225, 0.0),
 (1988, 895.8466186523438, 149.65235900878906, 61.493255615234375, 450.4956970214844, 493.1164245605469, 0.0, 17205.849609375, 220.8395233154297, 891.13330078125, 686.12744140625, 101.2978744506836, 0.025784092023968697, 0.04415411874651909, 3.241307258605957, 5.892490386962891, 13.989458084106445, 0.030675839632749557, 1.7415385246276855, 0.0),
 (1989, 930.10546875, 111.37128448486328, 57.6666145324707, 418.1727600097656, 474.9247741699219, 0.0, 17915.3359375, 208.58026123046875, 805.931884765625, 609.6959838867188, 74.79584503173828, 0.016387958079576492, 0.04736720025539398, 3.692014217376709, 5.3133368492126465, 10.229286193847656, 0.025520162656903267, 1.2660586833953857, 0.0),
 (1990, 751.4553833007812, 102.00208282470703, 54.310569763183594, 409.75189208984375, 435.1587829589844, 0.0, 16842.517578125, 213.63233947753906, 966.4890747070312, 589.3450317382812, 73.0428695678711, 0.007093863561749458, 0.04154253378510475, 3.0770206451416016, 5.872688293457031, 9.7684326171875, 0.025202790275216103, 1.2055107355117798, 0.0),
 (1991, 984.4703369140625, 86.0814437866211, 57.263160705566406, 446.9371337890625, 494.8575439453125, 0.0, 17945.25390625, 227.4623565673828, 853.9752197265625, 614.113037109375, 57.25899124145508, 0.03452887013554573, 0.03923920914530754, 3.1546146869659424, 5.416111946105957, 10.39381217956543, 0.018846388906240463, 1.2962639331817627, 0.0),
 (1992, 907.9463500976562, 147.8258819580078, 69.50972747802734, 557.2625122070312, 585.3338623046875, 0.0, 17973.1796875, 211.62164306640625, 799.1640625, 803.9385986328125, 103.30835723876953, 0.0680178850889206, 0.04302997142076492, 2.8922343254089355, 5.0419416427612305, 12.557315826416016, 0.04092651605606079, 1.5565334558486938, 0.0),
 (1993, 1057.7733154296875, 110.49251556396484, 63.801429748535156, 483.8179626464844, 531.8867797851562, 0.0, 19065.50390625, 240.46385192871094, 788.5387573242188, 684.6873779296875, 79.18535614013672, 0.04917503893375397, 0.04484313726425171, 3.9604244232177734, 5.065386772155762, 11.722579956054688, 0.02717497944831848, 1.4737484455108643, 0.0),
 (1994, 802.126220703125, 148.6778106689453, 52.7576904296875, 400.746337890625, 422.8682556152344, 0.0, 16865.736328125, 198.03636169433594, 857.4459838867188, 625.0359497070312, 113.71439361572266, 0.028455762192606926, 0.0350465402007103, 2.4140448570251465, 5.292174816131592, 12.538750648498535, 0.042000290006399155, 1.5544071197509766, 0.0),
 (1995, 696.852783203125, 98.80789947509766, 51.855560302734375, 378.6873779296875, 416.10601806640625, 0.0, 17348.3203125, 161.5633544921875, 713.6220092773438, 549.5087890625, 72.02813720703125, 0.002065235050395131, 0.040876422077417374, 2.958998441696167, 4.826737403869629, 8.771008491516113, 0.0371343195438385, 1.0821913480758667, 0.0),
 (1996, 799.9674682617188, 97.72754669189453, 44.8787841796875, 375.7298889160156, 403.7558288574219, 0.0, 18504.6796875, 159.91493225097656, 652.8770141601562, 538.9281616210938, 71.10895538330078, 0.008741110563278198, 0.03844992071390152, 2.909437417984009, 4.715249538421631, 10.309883117675781, 0.038051556795835495, 1.2813310623168945, 0.0),
 (1997, 689.3775024414062, 144.33688354492188, 47.68714904785156, 331.7184143066406, 376.2088317871094, 0.0, 16656.51171875, 191.31271362304688, 879.6626586914062, 542.03857421875, 120.72978973388672, 0.006449953652918339, 0.036036740988492966, 2.933741807937622, 5.032675266265869, 10.59711742401123, 0.0641491636633873, 1.305995225906372, 0.0),
 (1998, 843.460205078125, 81.3304672241211, 50.13521957397461, 389.658203125, 417.9104919433594, 0.0, 17480.861328125, 187.15975952148438, 714.4786987304688, 542.2412719726562, 60.09383773803711, 0.010638575069606304, 0.0409969836473465, 2.6642813682556152, 4.58079719543457, 8.4873685836792, 0.0328521765768528, 1.0512081384658813, 0.0),
 (1999, 644.3016357421875, 87.43292236328125, 39.094749450683594, 267.0400390625, 290.3387451171875, 0.0, 17345.736328125, 186.38597106933594, 848.9964599609375, 409.5931396484375, 70.29879760742188, 0.0020547746680676937, 0.035180483013391495, 2.129371166229248, 4.7743120193481445, 9.236139297485352, 0.03823297470808029, 1.133136510848999, 0.0),
 (2000, 497.9516296386719, 55.76639175415039, 40.30270004272461, 267.898681640625, 298.99395751953125, 0.0, 15240.1708984375, 176.56817626953125, 953.6580810546875, 378.92376708984375, 40.63188934326172, 0.0004136939824093133, 0.03624379262328148, 2.1420018672943115, 4.5201005935668945, 6.501877784729004, 0.030258269980549812, 0.7960548400878906, 0.0),
 (2001, 512.2509155273438, 58.428131103515625, 37.93268585205078, 243.51673889160156, 278.8904724121094, 0.0, 13922.068359375, 182.05116271972656, 1052.4482421875, 353.8802795410156, 40.51580047607422, 0.0005293001304380596, 0.03325581178069115, 2.214243173599243, 4.523447513580322, 6.893718242645264, 0.02934359200298786, 0.8467285633087158, 0.0),
 (2002, 702.0293579101562, 51.35315704345703, 47.55949020385742, 329.1170959472656, 377.5760803222656, 0.0, 13969.1435546875, 191.78431701660156, 980.2434692382812, 445.7998962402344, 33.742919921875, 0.000909165944904089, 0.03926758095622063, 2.83644962310791, 4.924394130706787, 7.660653114318848, 0.022082224488258362, 0.9403820633888245, 0.0),
 (2003, 729.9442138671875, 79.34848022460938, 52.159217834472656, 367.61334228515625, 393.82794189453125, 0.0, 16017.6982421875, 208.44747924804688, 954.4824829101562, 519.2665405273438, 54.75025939941406, 0.0013004285283386707, 0.03681840002536774, 2.4462573528289795, 4.770512104034424, 10.961112976074219, 0.034094080328941345, 1.3442833423614502, 0.0),
 (2004, 818.3781127929688, 79.15890502929688, 52.84273910522461, 352.75146484375, 412.0467529296875, 0.0, 16572.177734375, 208.24957275390625, 947.5720825195312, 504.1688537597656, 55.98431396484375, 0.0008061174303293228, 0.03870350494980812, 2.5637130737304688, 4.9130730628967285, 10.075298309326172, 0.028750907629728317, 1.2400538921356201, 0.0),
 (2005, 855.0092163085938, 112.44221496582031, 55.701541900634766, 415.2920227050781, 454.7132568359375, 0.0, 16346.92578125, 187.91116333007812, 857.3857421875, 605.7342529296875, 79.50537872314453, 0.0016020974144339561, 0.03877594321966171, 2.619595527648926, 4.631598949432373, 11.54205322265625, 0.055334512144327164, 1.4254027605056763, 0.0),
 (2006, 612.2903442382812, 118.15250396728516, 47.17096710205078, 325.51104736328125, 350.234375, 0.0, 14916.3046875, 199.26913452148438, 961.9083862304688, 509.4456787109375, 85.45063781738281, 0.0009314047638326883, 0.0368029810488224, 2.495469093322754, 4.62200403213501, 10.119010925292969, 0.06135867163538933, 1.2458702325820923, 0.0),
 (2007, 822.1746826171875, 88.14993286132812, 57.76415252685547, 408.3523864746094, 459.4039611816406, 0.0, 15647.421875, 197.01266479492188, 914.8236694335938, 576.3359985351562, 61.38154220581055, 0.006100356578826904, 0.03540681302547455, 2.6130831241607666, 4.722094535827637, 10.23675537109375, 0.04288588836789131, 1.2825894355773926, 0.0),
 (2008, 740.0899658203125, 57.794124603271484, 47.352195739746094, 321.425048828125, 355.2304382324219, 0.0, 15412.9677734375, 223.11538696289062, 1074.16943359375, 445.3414306640625, 38.68281936645508, 0.0009090701350942254, 0.034710828214883804, 2.4541854858398438, 4.7301506996154785, 7.13970947265625, 0.023224985226988792, 0.8808335065841675, 0.0),
 (2009, 1040.9012451171875, 128.0185546875, 67.97464752197266, 485.57733154296875, 548.677978515625, 0.0, 17289.611328125, 242.2028045654297, 921.8801879882812, 706.55517578125, 89.84158325195312, 0.026919061318039894, 0.04037037119269371, 2.8515422344207764, 4.785006046295166, 12.62111759185791, 0.05838346853852272, 1.568415880203247, 0.0),
 (2010, 905.66845703125, 126.46719360351562, 71.5470199584961, 516.8490600585938, 526.5103759765625, 0.0, 17295.349609375, 259.1895751953125, 900.2888793945312, 743.0734252929688, 93.37418365478516, 0.06076650694012642, 0.0399772934615612, 2.358428955078125, 4.7778496742248535, 10.460490226745605, 0.05550825968384743, 1.2955186367034912, 0.0)]

### 3. Récupération des données pour des colonnes spécifiques

Dans de nombreux cas, il n'est pas nécessaire d'extraire toutes les colonnes lors d'une instruction SELECT. 

Vous pouvez donc sélectionner et choisir uniquement les colonnes qui vous intéressent. 

La requête suivante extrait uniquement les colonnes ***YR***, ***PREC_mm*** et ***PET_mm***:

In [7]:
%sql SELECT YR, PREC_mm, PET_mm From watershed_yearly

 * sqlite:////content/gdrive/MyDrive/Partage/Notebooks_Serie_1/demo.db3
Done.

[(1981, 895.6051025390625, 840.6874389648438),
 (1982, 884.670654296875, 872.07470703125),
 (1983, 816.6605224609375, 797.04736328125),
 (1984, 867.5743408203125, 911.25634765625),
 (1985, 637.7255249023438, 990.8557739257812),
 (1986, 733.8412475585938, 977.513427734375),
 (1987, 1007.8944702148438, 841.0055541992188),
 (1988, 895.8466186523438, 891.13330078125),
 (1989, 930.10546875, 805.931884765625),
 (1990, 751.4553833007812, 966.4890747070312),
 (1991, 984.4703369140625, 853.9752197265625),
 (1992, 907.9463500976562, 799.1640625),
 (1993, 1057.7733154296875, 788.5387573242188),
 (1994, 802.126220703125, 857.4459838867188),
 (1995, 696.852783203125, 713.6220092773438),
 (1996, 799.9674682617188, 652.8770141601562),
 (1997, 689.3775024414062, 879.6626586914062),
 (1998, 843.460205078125, 714.4786987304688),
 (1999, 644.3016357421875, 848.9964599609375),
 (2000, 497.9516296386719, 953.6580810546875),
 (2001, 512.2509155273438, 1052.4482421875),
 (2002, 702.0293579101562, 980.2434692382812),
 (2003, 729.9442138671875, 954.4824829101562),
 (2004, 818.3781127929688, 947.5720825195312),
 (2005, 855.0092163085938, 857.3857421875),
 (2006, 612.2903442382812, 961.9083862304688),
 (2007, 822.1746826171875, 914.8236694335938),
 (2008, 740.0899658203125, 1074.16943359375),
 (2009, 1040.9012451171875, 921.8801879882812),
 (2010, 905.66845703125, 900.2888793945312)]

### 4. Comment faire quelques calculs dans les instructions SELECT

L'instruction SELECT peut faire bien plus que simplement sélectionner des colonnes.

Parfois, nous sommes également intéressés par la relation entre les colonnes. Cela peut être fait avec des expressions dans les instructions SELECT. 

Par exemple, j'aimerais voir la différence entre les colonnes ***PREC_mm*** et ***PET_mm*** (en utilisant l'opérateur moins **-**). 

Vous pouvez également essayer d'autres opérateurs tels que +, *, / ou %.

In [8]:
%sql SELECT YR, PREC_mm, PET_mm, PET_mm-PREC_mm From watershed_yearly

 * sqlite:////content/gdrive/MyDrive/Partage/Notebooks_Serie_1/demo.db3
Done.

[(1981, 895.6051025390625, 840.6874389648438, -54.91766357421875),
 (1982, 884.670654296875, 872.07470703125, -12.595947265625),
 (1983, 816.6605224609375, 797.04736328125, -19.6131591796875),
 (1984, 867.5743408203125, 911.25634765625, 43.6820068359375),
 (1985, 637.7255249023438, 990.8557739257812, 353.1302490234375),
 (1986, 733.8412475585938, 977.513427734375, 243.67218017578125),
 (1987, 1007.8944702148438, 841.0055541992188, -166.888916015625),
 (1988, 895.8466186523438, 891.13330078125, -4.71331787109375),
 (1989, 930.10546875, 805.931884765625, -124.173583984375),
 (1990, 751.4553833007812, 966.4890747070312, 215.03369140625),
 (1991, 984.4703369140625, 853.9752197265625, -130.4951171875),
 (1992, 907.9463500976562, 799.1640625, -108.78228759765625),
 (1993, 1057.7733154296875, 788.5387573242188, -269.23455810546875),
 (1994, 802.126220703125, 857.4459838867188, 55.31976318359375),
 (1995, 696.852783203125, 713.6220092773438, 16.76922607421875),
 (1996, 799.9674682617188, 652.8770141601562, -147.0904541015625),
 (1997, 689.3775024414062, 879.6626586914062, 190.28515625),
 (1998, 843.460205078125, 714.4786987304688, -128.98150634765625),
 (1999, 644.3016357421875, 848.9964599609375, 204.69482421875),
 (2000, 497.9516296386719, 953.6580810546875, 455.7064514160156),
 (2001, 512.2509155273438, 1052.4482421875, 540.1973266601562),
 (2002, 702.0293579101562, 980.2434692382812, 278.214111328125),
 (2003, 729.9442138671875, 954.4824829101562, 224.53826904296875),
 (2004, 818.3781127929688, 947.5720825195312, 129.1939697265625),
 (2005, 855.0092163085938, 857.3857421875, 2.37652587890625),
 (2006, 612.2903442382812, 961.9083862304688, 349.6180419921875),
 (2007, 822.1746826171875, 914.8236694335938, 92.64898681640625),
 (2008, 740.0899658203125, 1074.16943359375, 334.0794677734375),
 (2009, 1040.9012451171875, 921.8801879882812, -119.02105712890625),
 (2010, 905.66845703125, 900.2888793945312, -5.37957763671875)]

Plutôt pratique, mais le résultat est présenté comme un nouveau nom de colonne. 

Comme ça n'est pas très joli, nous allons lui donner un nouveau nom, en utilisant une ***instruction AS (=> un alias)***

In [9]:
%sql SELECT YR, PREC_mm, PET_mm, PET_mm-PREC_mm as PED_mm From watershed_yearly

 * sqlite:////content/gdrive/MyDrive/Partage/Notebooks_Serie_1/demo.db3
Done.

[(1981, 895.6051025390625, 840.6874389648438, -54.91766357421875),
 (1982, 884.670654296875, 872.07470703125, -12.595947265625),
 (1983, 816.6605224609375, 797.04736328125, -19.6131591796875),
 (1984, 867.5743408203125, 911.25634765625, 43.6820068359375),
 (1985, 637.7255249023438, 990.8557739257812, 353.1302490234375),
 (1986, 733.8412475585938, 977.513427734375, 243.67218017578125),
 (1987, 1007.8944702148438, 841.0055541992188, -166.888916015625),
 (1988, 895.8466186523438, 891.13330078125, -4.71331787109375),
 (1989, 930.10546875, 805.931884765625, -124.173583984375),
 (1990, 751.4553833007812, 966.4890747070312, 215.03369140625),
 (1991, 984.4703369140625, 853.9752197265625, -130.4951171875),
 (1992, 907.9463500976562, 799.1640625, -108.78228759765625),
 (1993, 1057.7733154296875, 788.5387573242188, -269.23455810546875),
 (1994, 802.126220703125, 857.4459838867188, 55.31976318359375),
 (1995, 696.852783203125, 713.6220092773438, 16.76922607421875),
 (1996, 799.9674682617188, 652.8770141601562, -147.0904541015625),
 (1997, 689.3775024414062, 879.6626586914062, 190.28515625),
 (1998, 843.460205078125, 714.4786987304688, -128.98150634765625),
 (1999, 644.3016357421875, 848.9964599609375, 204.69482421875),
 (2000, 497.9516296386719, 953.6580810546875, 455.7064514160156),
 (2001, 512.2509155273438, 1052.4482421875, 540.1973266601562),
 (2002, 702.0293579101562, 980.2434692382812, 278.214111328125),
 (2003, 729.9442138671875, 954.4824829101562, 224.53826904296875),
 (2004, 818.3781127929688, 947.5720825195312, 129.1939697265625),
 (2005, 855.0092163085938, 857.3857421875, 2.37652587890625),
 (2006, 612.2903442382812, 961.9083862304688, 349.6180419921875),
 (2007, 822.1746826171875, 914.8236694335938, 92.64898681640625),
 (2008, 740.0899658203125, 1074.16943359375, 334.0794677734375),
 (2009, 1040.9012451171875, 921.8801879882812, -119.02105712890625),
 (2010, 905.66845703125, 900.2888793945312, -5.37957763671875)]

En plus de nommer des expressions à l'aide d'alias, les alias peuvent également être utilisés pour renommer une colonne existante dans la requête. 

Par exemple, nous renommons ***PREC_mm*** en ***Precipitation_mm***.

*** Cependant, une telle opération n'affecte pas les données réelles et ne change pas le nom dans la table***.

Cela ne change finalement ce que vous voyez sur votre écran. 

Vous pouvez toujours essayer la requête "***SELECT * From Watershed_yearly***" pour vous assurer de la chose.

In [10]:
%sql SELECT YR, PREC_mm as Precipitation_mm, PET_mm, PET_mm-PREC_mm as PED_mm From watershed_yearly

 * sqlite:////content/gdrive/MyDrive/Partage/Notebooks_Serie_1/demo.db3
Done.

[(1981, 895.6051025390625, 840.6874389648438, -54.91766357421875),
 (1982, 884.670654296875, 872.07470703125, -12.595947265625),
 (1983, 816.6605224609375, 797.04736328125, -19.6131591796875),
 (1984, 867.5743408203125, 911.25634765625, 43.6820068359375),
 (1985, 637.7255249023438, 990.8557739257812, 353.1302490234375),
 (1986, 733.8412475585938, 977.513427734375, 243.67218017578125),
 (1987, 1007.8944702148438, 841.0055541992188, -166.888916015625),
 (1988, 895.8466186523438, 891.13330078125, -4.71331787109375),
 (1989, 930.10546875, 805.931884765625, -124.173583984375),
 (1990, 751.4553833007812, 966.4890747070312, 215.03369140625),
 (1991, 984.4703369140625, 853.9752197265625, -130.4951171875),
 (1992, 907.9463500976562, 799.1640625, -108.78228759765625),
 (1993, 1057.7733154296875, 788.5387573242188, -269.23455810546875),
 (1994, 802.126220703125, 857.4459838867188, 55.31976318359375),
 (1995, 696.852783203125, 713.6220092773438, 16.76922607421875),
 (1996, 799.9674682617188, 652.8770141601562, -147.0904541015625),
 (1997, 689.3775024414062, 879.6626586914062, 190.28515625),
 (1998, 843.460205078125, 714.4786987304688, -128.98150634765625),
 (1999, 644.3016357421875, 848.9964599609375, 204.69482421875),
 (2000, 497.9516296386719, 953.6580810546875, 455.7064514160156),
 (2001, 512.2509155273438, 1052.4482421875, 540.1973266601562),
 (2002, 702.0293579101562, 980.2434692382812, 278.214111328125),
 (2003, 729.9442138671875, 954.4824829101562, 224.53826904296875),
 (2004, 818.3781127929688, 947.5720825195312, 129.1939697265625),
 (2005, 855.0092163085938, 857.3857421875, 2.37652587890625),
 (2006, 612.2903442382812, 961.9083862304688, 349.6180419921875),
 (2007, 822.1746826171875, 914.8236694335938, 92.64898681640625),
 (2008, 740.0899658203125, 1074.16943359375, 334.0794677734375),
 (2009, 1040.9012451171875, 921.8801879882812, -119.02105712890625),
 (2010, 905.66845703125, 900.2888793945312, -5.37957763671875)]